
server.port: 8081

logging.level.org.springframework.web: DEBUG

spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:h2:mem:test
    username: sa
    password: sa

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017